# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Inventory"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
#template_toolkit: TT


serializer: JSON

template: "template_toolkit"

#------ Handle Session
# session: "YAML"
session: Cookie

engines:
  template:
    template_toolkit:
      start_tag: '{%'
      end_tag:   '%}'
  JSON:
    allow_blessed: 1
    convert_blessed: 1
    allow_nonref: 1
    utf8: 1
  session:
    Cookie:
      secret_key: get thee hence to yonder cookie factory
# 604800 = 7 days
      default_duration: 604800
#  session:
#    YAML:
#      session_dir: "/tmp/app/inventory/sessions/"#lugins:



plugins:
    'Cache::CHI':
      driver: Memory
      global: 1

    Database:
        driver: 'SQLite'
        database: 'db/user.db'
#        host: 'localhost'
#        port: 3306
        username: ''
        password: ''
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 1
#        on_connect_do: ["SET NAMES 'utf8'",  "SET CHARACTER SET 'utf8'" ]
        log_queries: 1
#        handle_class: 'User::DB::Handle' 

